-- Rename tables to plural snake_case
ALTER TABLE "BusinessUnit" RENAME TO business_units;
ALTER TABLE "Survey" RENAME TO surveys;
ALTER TABLE "Role" RENAME TO roles;
ALTER TABLE "Question" RENAME TO questions;
ALTER TABLE "AnswerOption" RENAME TO answer_options;
ALTER TABLE "QuestionResult" RENAME TO question_results;
ALTER TABLE "CommunicationPreference" RENAME TO communication_preferences;
ALTER TABLE "User" RENAME TO users;
ALTER TABLE "Account" RENAME TO accounts;
ALTER TABLE "Session" RENAME TO sessions;
ALTER TABLE "VerificationToken" RENAME TO verification_tokens;
ALTER TABLE "UsageMetrics" RENAME TO usage_metrics;

-- Rename many-to-many join tables
ALTER TABLE "_QuestionToRole" RENAME TO _question_to_role;
ALTER TABLE "_UserRole" RENAME TO _user_role;

-- Rename columns to snake_case
ALTER TABLE surveys RENAME COLUMN "surveyName" TO survey_name;
ALTER TABLE surveys RENAME COLUMN "surveyDate" TO survey_date;

ALTER TABLE roles RENAME COLUMN "default" TO is_default;

ALTER TABLE questions RENAME COLUMN "surveyId" TO survey_id;
ALTER TABLE questions RENAME COLUMN "questionText" TO question_text;

ALTER TABLE answer_options RENAME COLUMN "option" TO option_value;

ALTER TABLE question_results RENAME COLUMN "userId" TO user_id;
ALTER TABLE question_results RENAME COLUMN "questionId" TO question_id;
ALTER TABLE question_results RENAME COLUMN "answerId" TO answer_id;

ALTER TABLE communication_preferences RENAME COLUMN "userId" TO user_id;

ALTER TABLE users RENAME COLUMN "emailVerified" TO email_verified;
ALTER TABLE users RENAME COLUMN "businessUnitId" TO business_unit_id;

ALTER TABLE accounts RENAME COLUMN "userId" TO user_id;
ALTER TABLE accounts RENAME COLUMN "providerAccountId" TO provider_account_id;

ALTER TABLE sessions RENAME COLUMN "sessionToken" TO session_token;
ALTER TABLE sessions RENAME COLUMN "userId" TO user_id;

ALTER TABLE usage_metrics RENAME COLUMN "createdAt" TO created_at;

-- Drop old foreign key constraints
ALTER TABLE users DROP CONSTRAINT "User_businessUnitId_fkey";
ALTER TABLE question_results DROP CONSTRAINT "QuestionResult_userId_fkey";
ALTER TABLE question_results DROP CONSTRAINT "QuestionResult_questionId_fkey";
ALTER TABLE question_results DROP CONSTRAINT "QuestionResult_answerId_fkey";

-- Add new foreign key constraints with updated names
ALTER TABLE users ADD CONSTRAINT business_unit_user FOREIGN KEY (business_unit_id) REFERENCES business_units(id) ON DELETE SET NULL;
ALTER TABLE question_results ADD CONSTRAINT question_result_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE question_results ADD CONSTRAINT question_result_question FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE;
ALTER TABLE question_results ADD CONSTRAINT question_result_answer_option FOREIGN KEY (answer_id) REFERENCES answer_options(id) ON DELETE CASCADE;




-- AUTOGENERATED BY PRISMA
-- DropForeignKey
ALTER TABLE "question_results" DROP CONSTRAINT "question_result_answer_option";

-- DropForeignKey
ALTER TABLE "question_results" DROP CONSTRAINT "question_result_question";

-- DropForeignKey
ALTER TABLE "question_results" DROP CONSTRAINT "question_result_user";

-- DropForeignKey
ALTER TABLE "users" DROP CONSTRAINT "business_unit_user";

-- AlterTable
ALTER TABLE "accounts" RENAME CONSTRAINT "Account_pkey" TO "accounts_pkey";

-- AlterTable
ALTER TABLE "answer_options" RENAME CONSTRAINT "AnswerOption_pkey" TO "answer_options_pkey";

-- AlterTable
ALTER TABLE "business_units" RENAME CONSTRAINT "BusinessUnit_pkey" TO "business_units_pkey";

-- AlterTable
ALTER TABLE "communication_preferences" RENAME CONSTRAINT "CommunicationPreference_pkey" TO "communication_preferences_pkey";

-- AlterTable
ALTER TABLE "question_results" RENAME CONSTRAINT "QuestionResult_pkey" TO "question_results_pkey";

-- AlterTable
ALTER TABLE "questions" RENAME CONSTRAINT "Question_pkey" TO "questions_pkey";

-- AlterTable
ALTER TABLE "roles" RENAME CONSTRAINT "Role_pkey" TO "roles_pkey";

-- AlterTable
ALTER TABLE "sessions" RENAME CONSTRAINT "Session_pkey" TO "sessions_pkey";

-- AlterTable
ALTER TABLE "surveys" RENAME CONSTRAINT "Survey_pkey" TO "surveys_pkey";

-- AlterTable
ALTER TABLE "usage_metrics" RENAME CONSTRAINT "UsageMetrics_pkey" TO "usage_metrics_pkey";

-- AlterTable
ALTER TABLE "users" RENAME CONSTRAINT "User_pkey" TO "users_pkey";

-- RenameForeignKey
ALTER TABLE "accounts" RENAME CONSTRAINT "Account_userId_fkey" TO "accounts_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "communication_preferences" RENAME CONSTRAINT "CommunicationPreference_userId_fkey" TO "communication_preferences_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "questions" RENAME CONSTRAINT "Question_surveyId_fkey" TO "questions_survey_id_fkey";

-- RenameForeignKey
ALTER TABLE "sessions" RENAME CONSTRAINT "Session_userId_fkey" TO "sessions_user_id_fkey";

-- AddForeignKey
ALTER TABLE "question_results" ADD CONSTRAINT "question_results_answer_id_fkey" FOREIGN KEY ("answer_id") REFERENCES "answer_options"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "question_results" ADD CONSTRAINT "question_results_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "question_results" ADD CONSTRAINT "question_results_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_business_unit_id_fkey" FOREIGN KEY ("business_unit_id") REFERENCES "business_units"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- RenameIndex
ALTER INDEX "_QuestionToRole_AB_unique" RENAME TO "_question_to_role_AB_unique";

-- RenameIndex
ALTER INDEX "_QuestionToRole_B_index" RENAME TO "_question_to_role_B_index";

-- RenameIndex
ALTER INDEX "_UserRole_AB_unique" RENAME TO "_user_role_AB_unique";

-- RenameIndex
ALTER INDEX "_UserRole_B_index" RENAME TO "_user_role_B_index";

-- RenameIndex
ALTER INDEX "Account_provider_providerAccountId_key" RENAME TO "accounts_provider_provider_account_id_key";

-- RenameIndex
ALTER INDEX "BusinessUnit_unit_key" RENAME TO "business_units_unit_key";

-- RenameIndex
ALTER INDEX "CommunicationPreference_userId_key" RENAME TO "communication_preferences_user_id_key";

-- RenameIndex
ALTER INDEX "QuestionResult_userId_questionId_key" RENAME TO "question_results_user_id_question_id_key";

-- RenameIndex
ALTER INDEX "Session_sessionToken_key" RENAME TO "sessions_session_token_key";

-- RenameIndex
ALTER INDEX "Survey_surveyName_key" RENAME TO "surveys_survey_name_key";

-- RenameIndex
ALTER INDEX "User_email_key" RENAME TO "users_email_key";

-- RenameIndex
ALTER INDEX "VerificationToken_identifier_token_key" RENAME TO "verification_tokens_identifier_token_key";

-- RenameIndex
ALTER INDEX "VerificationToken_token_key" RENAME TO "verification_tokens_token_key";

-- DropIndex
DROP INDEX "verification_tokens_token_key";